# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Modifications Copyright 2026 JHopmann <Joerg@Hopmann.name>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  update_interval: 10s
  name: "deye-inverter"
  friendly_name: "Deye Inverter"
  modbus_hub_id_1: "modbus_1"    # Default Master
  modbus_hub_id_2: "modbus_2"    # Default Slave
  uart_hub_id_1: "modbus_uart_1" # Default Master
  uart_hub_id_2: "modbus_uart_2" # Default Slave
  nameprefix: ""   # No Prefix (Single-Inverter)
  prefix: ""       # No Prefix (Single-Inverter)

logger:
  level: WARN

api:
  encryption:
    key: ${api_key}
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: ${prefix}set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: ${fallback_password}

# ============ WEB-SERVER ============
web_server:
  port: 80

# ============ OTA ============
ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

modbus_controller:
  - id: ${modbus_controller_id}
    modbus_id: ${modbus_hub_id}
    setup_priority: -10
    update_interval: ${update_interval}
    #command_throttle: 60ms         # deprecated since 2026.8.0
    offline_skip_updates: 3

debug:
  update_interval: 60s

sensor:
  - platform: wifi_signal
    name: "${nameprefix}ESP WiFi Signal"
    id: "${prefix}esp_wifi_signal"
    icon: mdi:wifi
    update_interval: 60s
    entity_category: diagnostic
  - platform: uptime
    name: "${nameprefix}ESP Uptime"
    id: "${prefix}esp_uptime"
    type: seconds
    icon: mdi:timer-check
    update_interval: 60s
    entity_category: diagnostic
  - platform: debug
    free:
      name: "${nameprefix}ESP Heap Free"
      id: "${prefix}esp_heap_free"
      icon: mdi:memory
      entity_category: diagnostic
    block:
      name: "${nameprefix}ESP Heap Max Block"
      id: "${prefix}esp_heap_max_block"
      icon: mdi:memory
      entity_category: diagnostic
    loop_time:
      name: "${nameprefix}ESP Loop Time"
      id: "${prefix}esp_loop_time"
      icon: mdi:reload
      entity_category: diagnostic
    cpu_frequency:
      name: "${nameprefix}ESP CPU Frequency"
      id: "${prefix}esp_cpu_frequency"
      icon: mdi:cpu-32-bit
      unit_of_measurement: "MHz"
      filters:
        - multiply: 0.000001
      entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${nameprefix}ESP IP Address"
      id: "${prefix}esp_ip_address"
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "${nameprefix}ESP WiFi SSID"
      id: "${prefix}esp_wifi_ssid"
      icon: mdi:access-point
      entity_category: diagnostic
    mac_address:
      name: "${nameprefix}ESP Mac Address"
      id: "${prefix}esp_mac_address"
      icon: mdi:expansion-card
      entity_category: diagnostic
