# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Modifications Copyright 2026 JHopmann <Joerg@Hopmann.name>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  update_interval: 10s
  name: "deye-inverter"
  hostname: ${name}
  friendly_name: "Deye Inverter"
  modbus_hub_id_1: "modbus_1"    # Default Master
  modbus_hub_id_2: "modbus_2"    # Default Slave
  uart_hub_id_1: "modbus_uart_1" # Default Master
  uart_hub_id_2: "modbus_uart_2" # Default Slave
  nameprefix: ""   # No Prefix (Single-Inverter)
  prefix: ""       # No Prefix (Single-Inverter)

#esphome:
#  name: "${name}" #name: "deye-inverter"
#  #friendly_name: "DEYE Multiple Inverter"
#  #comment: "${device_description} by JHopmann https://github.com/JHopmann/esphome-deye-multi/"
#  project:
#    name: "JHopmann.deye-inverter-multi"
#    version: "0.1.3"

logger:
  level: WARN

api:
  encryption:
    key: ${api_key}
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: ${prefix}set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"

# ============ WEB-SERVER ============
web_server:
  port: 80

# ============ OTA ============
ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

modbus_controller:
  - id: ${modbus_controller_id}
    modbus_id: ${modbus_hub_id}
    setup_priority: -10
    update_interval: ${update_interval}
    #command_throttle: 60ms         # deprecated since 2026.8.0
    offline_skip_updates: 3

debug:
  update_interval: 60s

