# Copyright 2026 JHopmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# modbus_master.yaml
# This block should be loaded only in the master (or in a single inverter environment).
# It defines BOTH Modbus-Hubs and the UARTs.

substitutions:
  nameprefix: ""   # No Prefix (Single-Inverter)
  prefix: ""       # No Prefix (Single-Inverter)

  uart_tx_pin_slave: "GPIO17"
  uart_rx_pin_slave: "GPIO04"
  uart_flow_control_pin_slave: "GPIO16"

esphome:
  name: "deye-inverter"
  friendly_name: "DEYE Multiple Inverter"
  comment: "${device_description} by JHopmann https://github.com/JHopmann/esphome-deye-multi/"
  project:
    name: "JHopmann.deye-inverter-multi"
    version: "0.1.3"
  devices:
    - id: ${master_device_id}
      name: "Inverter Master"
    - id: ${slave_device_id}
      name: "Inverter Slave"

modbus:
  - id: modbus_1
    uart_id: modbus_uart_1
    #turnaround_time: 250ms    # since 2026.8.0
    send_wait_time: 250ms      # will be removed when turnaround_time is well established in 2027.2.0
  - id: modbus_2
    uart_id: modbus_uart_2
    #turnaround_time: 250ms    # since 2026.8.0
    send_wait_time: 250ms      # will be removed when turnaround_time is well established in 2027.2.0

uart:
  - id: modbus_uart_1
    tx_pin: ${uart_tx_pin_master}
    rx_pin: ${uart_rx_pin_master}
    flow_control_pin: ${uart_flow_control_pin_master}
    baud_rate: 9600
    stop_bits: 1
    data_bits: 8
    parity: NONE
  - id: modbus_uart_2
    tx_pin: ${uart_tx_pin_slave}
    rx_pin: ${uart_rx_pin_slave}
    flow_control_pin: ${uart_flow_control_pin_slave}
    baud_rate: 9600
    stop_bits: 1
    data_bits: 8
    parity: NONE
    
sensor:
    - platform: wifi_signal
      name: "ESP WiFi Signal"
      id: "esp_wifi_signal"
      icon: mdi:wifi
      update_interval: 60s
      entity_category: diagnostic
    - platform: uptime
      name: "ESP Uptime"
      id: "esp_uptime"
      type: seconds
      icon: mdi:timer-check
      update_interval: 60s
      entity_category: diagnostic
    - platform: debug
      free:
        name: "ESP Heap Free"
        id: "esp_heap_free"
        icon: mdi:memory
        entity_category: diagnostic
      block:
        name: "ESP Heap Max Block"
        id: "esp_heap_max_block"
        icon: mdi:memory
        entity_category: diagnostic
      loop_time:
        name: "ESP Loop Time"
        id: "esp_loop_time"
        icon: mdi:reload
        entity_category: diagnostic
      cpu_frequency:
        name: "ESP CPU Frequency"
        id: "esp_cpu_frequency"
        icon: mdi:cpu-32-bit
        unit_of_measurement: "MHz"
        filters:
          - multiply: 0.000001
        entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP IP Address"
      id: "esp_ip_address"
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "ESP WiFi SSID"
      id: "esp_wifi_ssid"
      icon: mdi:access-point
      entity_category: diagnostic
    mac_address:
      name: "ESP Mac Address"
      id: "esp_mac_address"
      icon: mdi:expansion-card
      entity_category: diagnostic
