# Copyright 2025 Lewa-Reka & Harvey Dent
#
# Modifications Copyright 2026 JHopmann <Joerg@Hopmann.name>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# modbus_master.yaml
# This block should be loaded only in the master (or in a single inverter environment).
# It defines BOTH Modbus-Hubs and the UARTs.

substitutions:
  nameprefix: ""   # No Prefix (Single-Inverter)
  prefix: ""       # No Prefix (Single-Inverter)

select:
  - platform: modbus_controller
    id: "${prefix}energy_management_priority"
    device_id: ${device_id}
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Energy Management Priority"
    address: 243
    value_type: U_WORD
    icon: "mdi:priority-high"
    optionsmap:
      "Battery First": 0
      "Load First": 1

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${prefix}system_work_mode"
    device_id: ${device_id}
    name: "${nameprefix}System Work Mode"
    address: 244
    value_type: U_WORD
    icon: "mdi:cog"
    optionsmap:
      "Selling First": 0
      "Zero Export To Load": 1
      "Zero Export To CT": 2

binary_sensor:
  - platform: template
    name: "${nameprefix}Load Priority"
    device_id: ${device_id}
    lambda: return id(${prefix}energy_management_priority).current_option() == "Load First";
    icon: "mdi:priority-high"

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Solar Sell"
    id: "${prefix}switch_solar_sell"
    device_id: ${device_id}
    register_type: holding
    address: 247
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Microinverter Export cut-off"
    device_id: ${device_id}
    register_type: holding
    address: 280
    bitmask: 0
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Generator Peak Shaving Enable"
    device_id: ${device_id}
    register_type: holding
    address: 280
    bitmask: 4
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Grid Peak Shaving Enable"
    device_id: ${device_id}
    register_type: holding
    address: 280
    bitmask: 8
    icon: "mdi:transmission-tower"

number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${prefix}max_sell_power"
    device_id: ${device_id}
    name: "${nameprefix}Max Sell Power"
    unit_of_measurement: W
    device_class: power
    min_value: 0
    step: 1
    address: 245
    value_type: U_WORD
    mode: box
    icon: "mdi:cash-multiple"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Max Solar Power"
    id: "${prefix}max_solar_power"
    device_id: ${device_id}
    unit_of_measurement: W
    device_class: power
    min_value: 0
    step: 1
    address: 53
    value_type: U_WORD
    mode: box
    icon: "mdi:solar-power"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Zero Export Power"
    id: "${prefix}zero_export_power"
    device_id: ${device_id}
    address: 206
    unit_of_measurement: "W"
    device_class: power
    value_type: U_WORD
    min_value: 20
    max_value: 500
    step: 1
    mode: box
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Generator Peak shaving"
    id: "${prefix}generator_peak_shaving_power"
    device_id: ${device_id}
    register_type: holding
    address: 292
    unit_of_measurement: "W"
    device_class: power
    value_type: U_WORD
    min_value: 0
    step: 1
    mode: box
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${nameprefix}Grid Peak Shaving Power"
    id: "${prefix}grid_peak_shaving_power"
    device_id: ${device_id}
    register_type: holding
    address: 293
    unit_of_measurement: "W"
    device_class: power
    value_type: U_WORD
    min_value: 0
    step: 1
    mode: box
    icon: "mdi:transmission-tower"
